server:
  port: ${PORT:5000}


spring:
  main:
    banner-mode: off

  datasource:
    url: jdbc:mysql://us-cdbr-east-02.cleardb.com/heroku_2f1e3f4c9d2c7
    username: b4abc91fe42680
    password: 200e8f80

  jpa:
    generate-ddl: true
    hibernate.ddl-auto: update
    show-sql: false

  mail:
    host:  smtp.gmail.com
    port: 587
    username: url.shortener.spring@gmail.com
    password: Url-1234
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000