spring:
  main:
    banner-mode: off

  datasource:
    url: jdbc:mysql://localhost:3306/url_shortener?seLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 123456

  jpa:
    generate-ddl: true
    hibernate.ddl-auto: create-drop
    show-sql: true
