spring:
  main:
    banner-mode: off

  datasource:
    url: jdbc:mysql://localhost:3306/url_shortener?seLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 123456

  jpa:
    generate-ddl: true
    hibernate.ddl-auto: create-drop
    show-sql: false

  mail:
    host:  smtp.gmail.com
    port: 587
    username: url.shortener.spring@gmail.com
    password: Url-1234
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000