server:
  port: ${PORT:5000}


spring:
  main:
    banner-mode: off

  datasource:
    url: jdbc:mysql://us-cdbr-east-06.cleardb.net:3306/heroku_0db43a596d5905f
    username: bf88a4c93d33b2
    password: 74ad14a3

  jpa:
    generate-ddl: true
    hibernate.ddl-auto: update
    show-sql: false

  mail:
    host:  smtp.gmail.com
    port: 587
    username: url.shortener.spring@gmail.com
    password: Url-1234
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000